domain_path: E:\HDLProjects\axi_stream_array_sum_microblaze\microblaze_platform\export\microblaze_platform\sw\standalone_microblaze_0
app_src_dir: C:\Xilinx\Vitis\2023.2\data\embeddedsw\lib\sw_apps\empty_application
template: empty_application
