#ifndef XPARAMETERS_H   /* prevent circular inclusions */
#define XPARAMETERS_H   /* by using protection macros */

#define XPAR_XAXI_STREAM_ADDER_NUM_INSTANCES 1

/* Definitions for peripheral AXIS_ADDER */
#define XPAR_AXIS_ADDER_COMPATIBLE xlnx,axi-stream-adder-1.0
#define XPAR_AXIS_ADDER_BASEADDR 0x40000
#define XPAR_AXIS_ADDER_HIGHADDR 0x4ffff

/* Canonical definitions for peripheral AXIS_ADDER */
#define XPAR_XAXI_STREAM_ADDER_0_BASEADDR 0x40000
#define XPAR_XAXI_STREAM_ADDER_0_HIGHADDR 0x4ffff
#define XPAR_XAXI_STREAM_ADDER_0_COMPATIBLE xlnx,axi-stream-adder-1.0

#define XPAR_XGPIO_NUM_INSTANCES 3

/* Definitions for peripheral SEG_14_BIT_IO */
#define XPAR_SEG_14_BIT_IO_COMPATIBLE xlnx,axi-gpio-2.0
#define XPAR_SEG_14_BIT_IO_BASEADDR 0x20000
#define XPAR_SEG_14_BIT_IO_HIGHADDR 0x2ffff
#define XPAR_SEG_14_BIT_IO_INTERRUPT_PRESENT 0x0
#define XPAR_SEG_14_BIT_IO_IS_DUAL 0x0
#define XPAR_SEG_14_BIT_IO_GPIO_WIDTH 0xe

/* Canonical definitions for peripheral SEG_14_BIT_IO */
#define XPAR_XGPIO_0_BASEADDR 0x20000
#define XPAR_XGPIO_0_HIGHADDR 0x2ffff
#define XPAR_XGPIO_0_COMPATIBLE xlnx,axi-gpio-2.0
#define XPAR_XGPIO_0_GPIO_WIDTH 0xe
#define XPAR_XGPIO_0_INTERRUPT_PRESENT 0x0
#define XPAR_XGPIO_0_IS_DUAL 0x0

/* Definitions for peripheral LEDS_GPIO */
#define XPAR_LEDS_GPIO_COMPATIBLE xlnx,axi-gpio-2.0
#define XPAR_LEDS_GPIO_BASEADDR 0x30000
#define XPAR_LEDS_GPIO_HIGHADDR 0x3ffff
#define XPAR_LEDS_GPIO_INTERRUPT_PRESENT 0x0
#define XPAR_LEDS_GPIO_IS_DUAL 0x0
#define XPAR_LEDS_GPIO_GPIO_WIDTH 0x10

/* Canonical definitions for peripheral LEDS_GPIO */
#define XPAR_XGPIO_1_BASEADDR 0x30000
#define XPAR_XGPIO_1_HIGHADDR 0x3ffff
#define XPAR_XGPIO_1_COMPATIBLE xlnx,axi-gpio-2.0
#define XPAR_XGPIO_1_GPIO_WIDTH 0x10
#define XPAR_XGPIO_1_INTERRUPT_PRESENT 0x0
#define XPAR_XGPIO_1_IS_DUAL 0x0

/* Definitions for peripheral SWITCHES_GPIO */
#define XPAR_SWITCHES_GPIO_COMPATIBLE xlnx,axi-gpio-2.0
#define XPAR_SWITCHES_GPIO_BASEADDR 0x40000000
#define XPAR_SWITCHES_GPIO_HIGHADDR 0x4000ffff
#define XPAR_SWITCHES_GPIO_INTERRUPT_PRESENT 0x0
#define XPAR_SWITCHES_GPIO_IS_DUAL 0x0
#define XPAR_SWITCHES_GPIO_GPIO_WIDTH 0x10

/* Canonical definitions for peripheral SWITCHES_GPIO */
#define XPAR_XGPIO_2_BASEADDR 0x40000000
#define XPAR_XGPIO_2_HIGHADDR 0x4000ffff
#define XPAR_XGPIO_2_COMPATIBLE xlnx,axi-gpio-2.0
#define XPAR_XGPIO_2_GPIO_WIDTH 0x10
#define XPAR_XGPIO_2_INTERRUPT_PRESENT 0x0
#define XPAR_XGPIO_2_IS_DUAL 0x0

#define XPAR_XINTC_NUM_INSTANCES 1

/* Definitions for peripheral MICROBLAZE_0_AXI_INTC */
#define XPAR_MICROBLAZE_0_AXI_INTC_COMPATIBLE xlnx,axi-intc-4.1
#define XPAR_MICROBLAZE_0_AXI_INTC_BASEADDR 0x41200000
#define XPAR_MICROBLAZE_0_AXI_INTC_HIGHADDR 0x4120ffff
#define XPAR_MICROBLAZE_0_AXI_INTC_KIND_OF_INTR 0x1
#define XPAR_MICROBLAZE_0_AXI_INTC_IS_FAST 0x1
#define XPAR_MICROBLAZE_0_AXI_INTC_IVAR_RST_VAL 0x10
#define XPAR_MICROBLAZE_0_AXI_INTC_NUM_INTR_INPUTS 0x1
#define XPAR_MICROBLAZE_0_AXI_INTC_ADDR_WIDTH 0x20
#define XPAR_MICROBLAZE_0_AXI_INTC_OPTIONS 0x0
#define XPAR_MICROBLAZE_0_AXI_INTC_INTCTYPE 0x0
#define XPAR_MICROBLAZE_0_AXI_INTC_HANDLER_TABLE 0x0

/* Canonical definitions for peripheral MICROBLAZE_0_AXI_INTC */
#define XPAR_XINTC_0_BASEADDR 0x41200000
#define XPAR_XINTC_0_HIGHADDR 0x4120ffff
#define XPAR_XINTC_0_HANDLER_TABLE 0x0
#define XPAR_XINTC_0_ADDR_WIDTH 0x20
#define XPAR_XINTC_0_COMPATIBLE xlnx,axi-intc-4.1
#define XPAR_XINTC_0_IS_FAST 0x1
#define XPAR_XINTC_0_IVAR_RST_VAL 0x10
#define XPAR_XINTC_0_INTCTYPE 0x0
#define XPAR_XINTC_0_KIND_OF_INTR 0x1
#define XPAR_XINTC_0_NUM_INTR_INPUTS 0x1
#define XPAR_XINTC_0_OPTIONS 0x0

/* Definitions for peripheral AXI_FIFO_TO_ADDER */
#define XPAR_AXI_FIFO_TO_ADDER_BASEADDR 0x50000
#define XPAR_AXI_FIFO_TO_ADDER_HIGHADDR 0x50fff

/* Canonical definitions for peripheral AXI_FIFO_TO_ADDER */
#define XPAR_AXI_FIFO_MM_S_0_BASEADDR 0x50000
#define XPAR_AXI_FIFO_MM_S_0_HIGHADDR 0x50fff

/*  BOARD definition */
#define XPS_BOARD_BASYS3

#define XPAR_LMB_BRAM_0_BASEADDRESS 0x0
#define XPAR_LMB_BRAM_0_HIGHADDRESS 0x20000
#define XPAR_CPU_CORE_CLOCK_FREQ_HZ 100000000

#define XPAR_MICROBLAZE_ADDR_SIZE 32

/* Device ID */
#define XPAR_DEVICE_ID "7a35t"

#endif  /* end of protection macro */