
/*******************************************************************
*
* CAUTION: This file is automatically generated by HSI.
* Version: 2023.2
* DO NOT EDIT.
*
* Copyright (C) 2010-2023 Xilinx, Inc. All Rights Reserved.
* SPDX-License-Identifier: MIT 

* 
* Description: Driver configuration
*
*******************************************************************/

#include "xparameters.h"
#include "xaxi_stream_adder.h"

/*
* The configuration table for devices
*/

XAxi_stream_adder_Config XAxi_stream_adder_ConfigTable[XPAR_XAXI_STREAM_ADDER_NUM_INSTANCES] =
{
	{
		XPAR_AXIS_ADDER_DEVICE_ID,
		XPAR_AXIS_ADDER_S_AXI_AP_CONTROLS_BASEADDR
	}
};


