
 PARAMETER VERSION = 2.2.0


BEGIN OS
 PARAMETER OS_NAME = standalone
 PARAMETER OS_VER = 9.0
 PARAMETER PROC_INSTANCE = microblaze_0
 PARAMETER stdin = usb_uart
 PARAMETER stdout = usb_uart
END


BEGIN PROCESSOR
 PARAMETER DRIVER_NAME = cpu
 PARAMETER DRIVER_VER = 2.18
 PARAMETER HW_INSTANCE = microblaze_0
END


BEGIN DRIVER
 PARAMETER DRIVER_NAME = llfifo
 PARAMETER DRIVER_VER = 5.6
 PARAMETER HW_INSTANCE = axi_fifo_to_adder
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = axi_stream_adder
 PARAMETER DRIVER_VER = 1.0
 PARAMETER HW_INSTANCE = axis_adder
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = intc
 PARAMETER DRIVER_VER = 3.17
 PARAMETER HW_INSTANCE = interrupt_controller
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = gpio
 PARAMETER DRIVER_VER = 4.10
 PARAMETER HW_INSTANCE = leds_gpio
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = bram
 PARAMETER DRIVER_VER = 4.9
 PARAMETER HW_INSTANCE = microblaze_0_local_memory_dlmb_bram_if_cntlr
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = bram
 PARAMETER DRIVER_VER = 4.9
 PARAMETER HW_INSTANCE = microblaze_0_local_memory_ilmb_bram_if_cntlr
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = gpio
 PARAMETER DRIVER_VER = 4.10
 PARAMETER HW_INSTANCE = seg_14_bit_io
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = gpio
 PARAMETER DRIVER_VER = 4.10
 PARAMETER HW_INSTANCE = switches_gpio
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = uartlite
 PARAMETER DRIVER_VER = 3.9
 PARAMETER HW_INSTANCE = usb_uart
END


