set_property PACKAGE_PIN W7 [get_ports {seg_display[0]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {seg_display[0]}]
set_property PACKAGE_PIN W6 [get_ports {seg_display[1]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {seg_display[1]}]
set_property PACKAGE_PIN U8 [get_ports {seg_display[2]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {seg_display[2]}]
set_property PACKAGE_PIN V8 [get_ports {seg_display[3]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {seg_display[3]}]
set_property PACKAGE_PIN U5 [get_ports {seg_display[4]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {seg_display[4]}]
set_property PACKAGE_PIN V5 [get_ports {seg_display[5]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {seg_display[5]}]
set_property PACKAGE_PIN U7 [get_ports {seg_display[6]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {seg_display[6]}]

set_property PACKAGE_PIN V7 [get_ports seg_dp]							
	set_property IOSTANDARD LVCMOS33 [get_ports seg_dp]

set_property PACKAGE_PIN U2 [get_ports {seg_select[0]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {seg_select[0]}]
set_property PACKAGE_PIN U4 [get_ports {seg_select[1]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {seg_select[1]}]
set_property PACKAGE_PIN V4 [get_ports {seg_select[2]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {seg_select[2]}]
set_property PACKAGE_PIN W4 [get_ports {seg_select[3]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {seg_select[3]}]
	
set_property PACKAGE_PIN T18 [get_ports add_value]						
	set_property IOSTANDARD LVCMOS33 [get_ports add_value]